* DONE Set up project repository for collaboration (Henri).
  Set up the initial project repository for collaboration. Need some
  way to make sure everyone is on the same page so that we can make
  progress. 
* TODO Get simple recommendation scheme working for our dataset [0%]
  Before we can run our powerhouse method, we need to have a simple
  recommendation algorithm to run our dataset. This will ensure all
  the components of the system work as necessary before we plug in our
  high-powered algorithm.
** TODO Load/clean dataset
   Loading the dataset is complete but there is currently no true
   cleaning being done. Examples of things we may want to do are
   removing users/games with too few reviews, checking for any
   fuzzy matches which may be data entry mistakes.
** TODO Decide on simple recommendation algorithm
** TODO Run simple recommendation algorithm on toy dataset
** TODO Write more TODOs!
   Anything that needs to be done/thought about, write a TODO for
   it. It will help immensely with our project.
